name             'taller'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures taller'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'rbenv'
depends          'mysql'
depends          'ruby_build'
depends          'nginx'
depends          'ohai'
