name             'Taller'
maintainer       'Sergio'
maintainer_email 'smarquezs@gmail.com'
license          'All rights reserved'
description      'Installs/Configures nimrod'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1'
depends          'rbenv'
depends          'mysql'
depends          'ruby_build'
# depends          'ohai'
# depends          'nginx'
# depends          'java'
# depends          'mongodb'
# depends          'tomcat-solr'
# depends          'varnish'
# depends          'chef-splunk'
